mediumChallanges = [
    "Learn a new dance move from a stranger.",
    "Take a selfie with someone dressed in a unique costume.",
    "Trade a friendship bracelet with someone new.",
    "Get a band recommendation from a local.",
    "Find someone with a tattoo related to music.",
    "Help someone find their way around the festival.",
    "Ask a vendor how they got started.",
    "Find three different accents.",
    "Get a photo with someone holding a prop.",
    "Convince a friend to try a new food with you.",
    "Write down a lyric from a song you've never heard before.",
    "Find the highest point at the festival (if applicable).",
    "Learn one word in another language from a festival-goer.",
    "Give a shout-out to your favorite festival artist on social media.",
    "Find someone who travelled further than you to get here.",
    "Create a quick, collaborative drawing with a stranger.",
    "Find something that smells really good (other than food).",
    "Spot someone juggling or doing a similar skill.",
    "Start a conversation with someone about their outfit.",
    "Find a piece of art or an installation you haven't noticed before."
]
